### PR TITLE
Update issue_label_bot.yaml

### PR DESCRIPTION
**Pull request by hamelsmu**
I'm hoping this answers your question about how to alias .... let me know if this is what you wanted?

### CODE REVIEW

**Comment by hamelsmu** [comment]
> I am wondering how could I use different labels for recognized EX. Invalid Questions It puts invalid as a label @hamelsmu

Can you tell me what you mean by this?  What is a recognized EX?  What is EX?

**Comment by hamelsmu** [comment]
oops sorry wrong place

**Comment by DevAvanCodes** [comment]
@hamelsmu How would I add things like wontfix and type of labels I can customize

**Comment by hamelsmu** [comment]
I’m working on it … that is a bit harder

**Comment by DevAvanCodes** [comment]
Ok, thanks @hamelsmu

**Pull request merged**
